# Encrypted key doc
#   https://docs.travis-ci.com/user/encryption-keys
#
# Encrypted key commands
#   gem install travis
#   travis pubkey
#   travis encrypt DOCKER_PASSWORD=*********** --add
sudo: required
services:
- docker
env:
  global:
  - DOCKER_USERNAME=gjacquenot
  - secure: SBjR7919hbJIprFX6dFXji5BS+OU+POwB+rz+IHDx9yLLl5rietutb3K1nR3KrlKmozDKkaVZDCL9qtz6LxLNCMmugwlLtS3LHlPttEa0X2XdZnRpeBthnuyoN01In7Sx/32vzW3RaXzpOgu6E3ItTqF2EP2Abeh+1aVI0uyfk6QAlFGEVSKlNabIiBED6zh/mlC/gaf5NEYBo2ucQMT7WhHYU7NTizn6ZI9JQGAE+dQzrCds1w90bkeoA6dmgv4VwFiFlfPeoRuoVlbpSsHBuBeAZxEhppQrWm5iTNfeibLyFWuBXdp44+kVA4/xcUdqGu9/L4eSeF9JOayWTLvvfXBYbABd1C69JNLxyDb+epVwWOEnuPcu262Z6LZPBZJE5ln49Ty8DgZxWVgg2iaT07NdnD/WdaTtd32/j322CrowhkxFFrDAZ9gEEUzkwhZc3CXrEXn4d7bf1R+96ijwTtx3WBSkQS5NygH6FJVQ9yADnhIcVEfyMuc7ax8yi3Z8Pqs6FG5ItegNEiPrtH/ybjEVOzfVUhcr/axe369WOT7p69ZT1YC3zsl6/sY9lnLsh2sKKVUpkIFRpFmYWqqUYINwUuORWFTsHYKIlM4qZzwbGUnA+gSIH4VGnGUvjn2TkGqIv3QcXNRqb2pfX6nY1hlr856WVdPoHKHeI7MHHU=
before_install:
- echo "Before install"

before_script:
- docker pull gjacquenot/ssc_build || true
script:
- docker build --pull --cache-from gjacquenot/ssc_build --tag gjacquenot/ssc_build .
#  - docker run gjacquenot/ssc_build
after_script:
  - docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker login -u $DOCKER_USERNAME -p
  $DOCKER_PASSWORD ; make push-image ; fi
notifications:
  email: true
